feat: pdf export, fixes #3
metricq/metricq-webview pull request #141
Opened 2022-02-11 13:55 UTC by AndyBuchwald

2022-02-25 15:15 UTC, AndyBuchwald commented
TODO: export button needs to be locked until analyze table is fully loaded

2022-03-10 15:37 UTC, kinnarr requested changes
Looks good overall. Just a few comments about code placement

2022-03-10 15:37 UTC, kinnarr commented on src/ui/analyze-popup.vue
> +import { mapState } from 'vuex'
Please remove the unused imports.

2022-03-10 15:37 UTC, kinnarr commented on src/store/index.js
>  Vue.use(AsyncComputed)
I would prefer to have this in app.js or in a new file imported from app.js. Unlike Vuex, these plugins are not dedicated to the store.

2022-03-10 15:37 UTC, kinnarr commented on src/store/index.js
> +  },
Please remove this if it is not from eslint

2022-03-10 15:37 UTC, kinnarr commented on src/ui/export-popup.vue
> +            :disabled="!pdfReady"
Do I also have to wait if I export an image without the table?

2022-03-10 15:37 UTC, kinnarr commented on src/ui/export-popup.vue
> +      const result = await this.waitNewCanvas()
Is this code only for the pdf export or for all exports?

2022-03-11 13:13 UTC, kinnarr requested changes
Please rebase and fix the conflict in store.js

2022-03-11 13:13 UTC, kinnarr commented on src/store/index.js
> -  },
Sorry, I just meant the line break.

2022-03-12 16:04 UTC, kinnarr approved these changes
LGTM

2022-03-14 09:13 UTC, merged