refactor & fix: combines all metrics/create calls into one and checks…
metricq/metricq-webview pull request #148
Opened 2022-05-06 11:54 UTC by AndyBuchwald

… whether metric has metadata, fixes #144

2022-05-06 12:33 UTC, AndyBuchwald commented
also fixes #140

2022-05-16 11:38 UTC, tilsche requested changes

2022-05-16 11:38 UTC, tilsche commented on src/MetricQWebView.js
> +      await this.store.dispatch('metrics/create', { metric: { ...oldMetric, name: metricBase, description: description, traces: [] } })
Now the boolean return value of `addMetric` is used, but a bool is never returned here.

2022-05-25 15:06 UTC, tilsche commented
@AndyBuchwald small hint. If you *rebase* then there is no extra commit. If there's an extra commit, you probably *merged* the `master` into branch

2022-05-25 15:06 UTC, merged